### ISSUE TITLE
Missing CLI usage example

### ISSUE THREAD

**Issue by jeremiahlee** [unstoppablecarl/metalsmith-navigation#10]
The Readme.md currently has an empty object for "metalsmith-navigation".

I thought that I would pass two keys: "navConfigs" and "settings", but it seems that I should only be passing navConfigs. How would I also pass settings?

**Comment by unstoppablecarl** [comment]
To be honest I have never used the CLI. I will look at it tomorrow.

**Comment by unstoppablecarl** [comment]
fixed in 0.2.1

**Comment by jeremiahlee** [comment]
Thanks for fixing! Minor note: navConfigs and navSettings should be in double quotes in the Readme to be valid JSON.
