### ISSUE TITLE
Current page flag

### ISSUE THREAD

**Issue by jeremiahlee** [unstoppablecarl/metalsmith-navigation#11]
Is there a way to identify the page in a navigation list as the page where the navigation list is being rendered? For example: on the "about" page, I want to change the style of the link to the "about" page in the navigation.

**Comment by unstoppablecarl** [comment]
The current page nav path can be retrieved using the `navConfig.pathProperty` property. Checking each nav object for a matching path will allow you to locate current one. A flag cannot be set on the nav objects directly as they are shared by all files that use them. I have updated the readme to explain the `navConfig.pathProperty` better.

Re-open this issue if you still need help.

**Comment by glen-84** [comment]
@unstoppablecarl Could you please elaborate a bit? I'm not sure what to compare `path` or `nav_path` with. (I also don't really understand the difference between path/nav_path, children/nav_children, etc.)

**Comment by unstoppablecarl** [comment]
The `nav_path` will be set to the current file you are viewing. Have you looked at the examples? I think it is easier to understand than the readme. 

Look at this https://github.com/unstoppablecarl/metalsmith-navigation/blob/master/examples/generic/templates/_nav__children.html#L7

You will have to understand handlebars templates for it to make sense though. If you message me on google hangouts (use email in my profile) I would be happy to walk you through it.

**Comment by glen-84** [comment]
That link was very helpful. Thanks again Carl. =)
