### ISSUE TITLE
Detecting active on index.html

### ISSUE THREAD

**Issue by jmjf** [unstoppablecarl/metalsmith-navigation#13]
I'm using metalsmith-permalinks. Here are pertinent excerpts from build.js

```
var navConfigs = {
		primary: {
			sortBy: 'navOrder',
			includeDirs: true,
			filterProperty: 'navGroups'
		}
	},
	navSettings = {
		navListProperty: 'navs',
		permalinks: true
	};
...
	.use(permalinks({
		relative: false
	}))
	// process navigation tree
	.use(navigation(navConfigs, navSettings))
```

Trying to sort through how to determine the active menu item, I built the following template (simplified to focus on what seems to be the important data) and wrapped it in an `{{#each navs.primary}}` block.

testMenu.hbs
```
{{#if file}}
	FILE: name: {{name}} | path: {{path}} | @root.nav_path: {{@root.nav_path}} | @root.path: {{@root.path}}
{{else}}
	!FILE: {{name}}
{{/if}}
{{#if children}}
	CHILD:
	{{#each children}}
		{{> testMenu}}
	{{/each}}
	END-CHILD
{{/if}}
```

After examining the output on a few test pages, I decided that if path == @root.path, the current page is active. Here's a sample from the child page for products/product1.

```
NAV
		FILE: name:index.html | path: index.html | @root.nav_path: products/product1/index.html | @root.path: products/product1
		FILE: name:about | path: about | @root.nav_path: products/product1/index.html | @root.path: products/product1
		!FILE: products
		CHILD:
				FILE: name:product1 | path: products/product1 | @root.nav_path: products/product1/index.html | @root.path: products/product1
		END-CHILD
END-NAV
```
Which is all well and good and everything is consistent and easy until I look at the site's index.html. For index.html, I get

```
FILE: name: index.html | path: index.html | @root.nav_path: index.html | @root.path: 
```

My guess is transformPermalinks() is not stripping the file name from the root index.html. I'm wondering if there's a (sane) way to make it do that so testing for active is consistent for all pages. Adding the following into my local copy after line 409 seems to fix this without harming anything else, but I'm not sure if you see other possible consequences to important nav metadata. It seems like the only possible hole is the `node.parent`, which probably shouldn't exist for the root index.html anyway.

```
            } else if ((node.depth == 1) && (node.path == 'index.html')){
                node.path = "";
            }
```

If this seems reasonable, let me know and I can set up a PR.

**Comment by unstoppablecarl** [comment]
When you use permalinks the path `index.html` is changed to `''` (empty string). You usually need to do a special case to check for the root page. It varies depending on your setup though. I think in your case you just need to add a check into your template for something like `node.path === 'index.html' && !@root.path` If you need more help feel free to email me and we can chat. I would need to see more of your code to help.

**Comment by jmjf** [comment]
Just sent you email with gory details. Here's the short answer.

if `@root.nav_path === file.nav_path`, the node is the active node.

This seems to be true for permalink and no-permalink builds.

For anyone interested, gory details in a test case are at [https://github.com/jmjf/ms-nav-issue13](https://github.com/jmjf/ms-nav-issue13). I've also tested this approach in my real code and it looks right for both permalink and no-permalink builds there too.

Based on that, this is probably the best way to detect the active node for all cases. If you use the pathProperty option to change the name of nav_path, adjust accordingly.
