### ISSUE TITLE
Permalinks with mergeMatchingFilesAndDirs doesn't sort as expected.

### ISSUE THREAD

**Issue by jmjf** [unstoppablecarl/metalsmith-navigation#14]
In the example, swap the nav_order value on services.md and any other file. build-permalinks. The services item is still last.

In my test project, adding some console.logs to makeArraySortByFunc() as follows:
```
var makeArraySortByFunc = function(sortBy, usePermalinks){
    usePermalinks = usePermalinks || false;

    if(typeof sortBy !== 'function'){
        var sortByKey = sortBy;

        sortBy = function(node){
            if(node.file){
                node.sort = node.file[sortByKey];
/**/            console.log("sortBy:", node.name, node.file.navOrder);
                return node.file[sortByKey];
            }
        };

    } else {
        var sortByFunc = sortBy;
        sortBy = function(node){
            // first param is the expected metalsmith file object, node objecty is available as second param
            return sortByFunc(node.file, node);
        };
    }

    if(usePermalinks){
        var _sortBy = sortBy;
        sortBy = function(node){

            // if node is dir and has 1 child sort using that child node instead of the dir
            if(!node.file && node.children.length === 1){
/**/            console.log("parent:", node.name); 
                node = node.children[0];
/**/            if (!node.file) {console.log(node.name, "has no file");}
            }
            return _sortBy(node);
        };
    }

    return sortBy;
};
```
gets the following output
```
parent: about
sortBy: index.html 2
parent: contact
sortBy: index.html 6
parent: custom
sortBy: index.html 5
sortBy: index.html 1
parent: leadership
sortBy: index.html 3
sortBy: index.html 2                    <-- lodashSortBy happens here, I'm betting
sortBy: index.html 3
sortBy: index.html 5
sortBy: index.html 6
sortBy: index.html 4                    <-- products/index.html, no "parent" --> not permalink in sort
parent: product1
sortBy: index.html 3                    <-- then products/product1/index.html
```
where products is a directory at the same level as index.html, about, etc. with a products.md sibling, and products1 is a child of products.

Turning off permalinks, the output is
```
sortBy: about.html 2
sortBy: contact.html 6
sortBy: custom.html 5
sortBy: index.html 1
sortBy: leadership.html 3
sortBy: products.html 4
sortBy: product1.html 3
```
But here it's sorting the products.html file, which is pushed to build, not the directory node.

I think the issue is that permalinks builds products.md to products/index.html. That happens before navigation runs, so navigation doesn't find a mergeable sibling. makeArraySortByFunc() requires a single child to recognize a permalink folder, which isn't true because products has product1 as a child too. And we end up not recognizing that products is a permalink with additional children.

Somehow, the permalink dir node needs to get its index.html file attached regardless of how many children it has.

The rationale for this is that I need to apply metadata to products (sort key, menu item title, etc.) so I'm loading the metadata onto the sibling. The menu item for products is an href="#" dropdown item (using Bootstrap), so the page will never be accessed, only the children.

It's late. I'll look at this more tomorrow and update here.

**Comment by jmjf** [comment]
After kludging the code to get products' index.html attached to it, I think the following is correct.

> Somehow, the permalink dir node needs to get its index.html file attached regardless of how many children it has.

When I assign the index.html file to the products dir node's file, the menu sorts in the right order in my test.

I'll work on this and submit a PR when I have it resolved with a general approach.

**Comment by unstoppablecarl** [comment]
Closing as fork was last updated 9 months ago.
