### ISSUE TITLE
Path separator issues on windows

### ISSUE THREAD

**Issue by pavkriz** [unstoppablecarl/metalsmith-navigation#16]
On windows, only 2 levels are shown in All Nav tree in the example.

When in revert back to 833d857d3872475f902ded2c328a527a52b00db7, it works well and I see all 4 levels.

**Comment by unstoppablecarl** [comment]
That is strange. Can you check if `require('lodash.sortby')` is the problem?

**Comment by pavkriz** [comment]
I removed the content of the sortNodes function (to return the tree unmodified) and removed `require('lodash.sortby')` - without effect.

Maybe a hint: When I navigate manually to .../examples/generic/build/services/marketing/email.html (a page that is not displayed in the All Nav tree due to this issue) I see "Home / services\marketing / Email Marketing" in breadcrubs (see the string with backslash - it's a single item in the breadcrumbs path instead of two).

Note: I see backslashes in tree links (a-hrefs in produced HTML) in both versions (833d857d3872475f902ded2c328a527a52b00db7 and 0.2.4) but it's not an issue for me.

**Comment by martinvehmas** [comment]
This is not an issue regarding metalsmith-navigation. Its the output from metalsmith-markdown that is wrong.

I registrered an [Issue](https://github.com/segmentio/metalsmith-markdown/issues/15) and submitted a [Pull request](https://github.com/segmentio/metalsmith-markdown/pull/16) to metalsmith-markdown about this problem.
