### ISSUE TITLE
Wrong version on npm

### ISSUE THREAD

**Issue by martinvehmas** [unstoppablecarl/metalsmith-navigation#19]
Hi,

In commit c2b754dcae5564f018aebd391f8627c4ae6f47ff you changed the version to 0.2.5 and there is a 0.2.5 version on https://www.npmjs.com/package/metalsmith-navigation.

If I npm install version 0.2.5 I don’t get the latest version. The code is not the same as of commit c2b754dcae5564f018aebd391f8627c4ae6f47ff. 

The changes from Pull request #17 is not there.

Am I doing anything wrong or did the npm publish go wrong?

**Comment by unstoppablecarl** [comment]
Should be fixed now.
