### ISSUE TITLE
Relative navigation not working with permalinks?

### ISSUE THREAD

**Issue by kurtnz** [unstoppablecarl/metalsmith-navigation#23]
Not sure if I'm missing something but I can't get the relative navigation working with permalinks turned on.

I've downloaded the example and tried to get that working too but it doesn't spit out anything under the current page title in the _nav_relative.html file. 

What would I need to do to get this to work in the example?

**Comment by unstoppablecarl** [comment]
I don't think there is a way to do it right now. Permalinks make a lot of things act strangely. If you really need this email me or message me on the metalsmith slack.

**Comment by kurtnz** [comment]
No worries was just a little confused since there was the build-permalinks.js file in the example I thought I must have been doing something wrong.
