### ISSUE TITLE
Breadcrumb custom labels

### ISSUE THREAD

**Issue by ozum** [unstoppablecarl/metalsmith-navigation#24]
Hi,

Is it possible to have custom labels for breadcrumb text like fetching from title or any other metadata key?

For example:

|File|Breadcrumb|
|-|-|
|`main/sports-primary/index.html` | `Home > Sports`
|`main/sports-primary/soccer/index.html` | `Home > Sports > Football Video`
|`main/sports-primary/basketball/index.html` | `Home > Sports > Basketball Video`

**Comment by unstoppablecarl** [comment]
You should be able to access any metadata. See `file.title` on this line:

https://github.com/unstoppablecarl/metalsmith-navigation/blob/master/examples/generic/templates/_breadcrumbs.html#L20
