### ISSUE TITLE
Metalsmith-navigation is not cross-platform

### ISSUE THREAD

**Issue by SgtPooki** [unstoppablecarl/metalsmith-navigation#5]
The replaceDirsSeparator function is unnecessary, does not actually work for  windows machines, and is a waste of time for all non-windows machines.

For future reference, you would need to change ```var newKey = oldKey.replace(path.sep, "/"); ``` to ```var newKey = oldKey.replace('\\\\', "/");``` for this to properly replace the windows path separators. However, this still leaves an issue where you are not replacing all of the path separators, only the first ones. Usually, you would pass the 'g' flag to the replace function, but that is not supported on node, so you would actually need to do something like this: 
```
//no need to replace "/" with "/", so just check for "\\" and replace all occurrences.
var regex = /\\/g;
var newKey = oldKey.replace(regex, "/");  
```

And finally, there is no reason for us to even do all this work, because node will handle this all for us:
```
var path = require('path');
var filePathArray = filePath.split(path.sep);
var newFilePath = filePathArray.join('/'); // join with whatever you like here
```

This is much cleaner, more maintainable, and more future proof. If windows/mac/nix changes their file separators to @.. all joyent (or io.js) would need to do is update their path.sep implementation for that OS, and your code would still be good to go.

**Comment by unstoppablecarl** [comment]
There are other places in the code that are dependent on the use of `/` as a separator.
 - https://github.com/unstoppablecarl/metalsmith-navigation/blob/master/lib/index.js#L227
 - https://github.com/unstoppablecarl/metalsmith-navigation/blob/master/lib/index.js#L279

Also the end resulting paths for a website will need `/` as separators. The code in your PR will cause some cases to not work.

**Comment by SgtPooki** [comment]
Sure. I will get on that tonight.

**Comment by SgtPooki** [comment]
@unstoppablecarl this should be ready to go now, good catch. I tested and confirmed that my code, SgtPooki/MetalSmith-Demo, and the metalsmith-navigation examples both work. Let me know if you spot anything to the contrary!
