### ISSUE TITLE
Single item navigation with `metalsmith-watch`

### ISSUE THREAD

**Issue by sklar** [unstoppablecarl/metalsmith-navigation#7]
Hey,

how can I make this plugin work properly with [metalsmith-watch](https://github.com/FWeinb/metalsmith-watch) pls?
It generates navigation with only one (currently changed file) item.

Thanks!

**Comment by unstoppablecarl** [comment]
Can you post your use case?

**Comment by sklar** [comment]
Sure, here is testing repository [test-metalsmith](https://github.com/sklar/test-metalsmith).
[Livereload](http://livereload.com/extensions/) required..
```
npm install && grunt build
```

**Comment by unstoppablecarl** [comment]
This looks like a feature of metalsmith-watch. It only regenerates a file that is changed.

**Comment by sklar** [comment]
Well I don't think so..

What about [metalsmith-collections](https://github.com/segmentio/metalsmith-collections) then?
It works as designed even with `metalsmith-watch` plugin.

Maybe I'm mixing apples and pears, but let's have a simple use case - blog (300+ pages).
I'm about to add a new page that's not a part of any navigation or any collection (e.g. post archive or relevant posts). There's a content, primary navigation (of course) and let's say list of top rated posts on the new page.

So I'll create a file, fill in a markdown and save it.
Metalsmith (with `metalsmith-watch` in stack) will correctly send down the pipe only the new page with compiled content, top rated post list (`metalsmith-collections`) and empty navigation (`metalsmith-navigation`).

If I want to have the navigation in the new fancy page then I'll have to regenerate all those 300+ pages.

I think that's very uneffecient and it's not `metalsmith-watch` issue.
Do you have any suggestion to solve it pls?

Thanks a lot Carl!

**Comment by unstoppablecarl** [comment]
I looked at your example code again. I am not sure why you are running into this problem, but I am not familiar with a lot of the things you are doing. If you email me we can chat and figure it out.
